[package]
name = "rs-fsmode2enum4du"
version = "0.1.0"
edition = "2024"

exclude = [
]

[profile.release-wasi]
inherits = "release"
lto = true
strip = true
opt-level = 's'
codegen-units = 1

[[bin]]
name = "fsmode2enum4du"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
unwrap_used = "forbid"
expect_used = "forbid"
panic = "forbid"
